""" Use this to convert the qanet predictions into
the standard squad JSON format to evaluation
"""

import sys
import json


def read_json(file_path):
    data = {}
    with open(file_path, "r", encoding="utf-8") as f:
        for ctr, line in enumerate(f.readlines()):
            data.update(json.loads(line))
        assert len(data.keys()) == ctr + 1
    return data


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise AssertionError(
            "Takes in exactly 1 argument: path to prediction file generated by qanet"
        )
    file_path = sys.argv[1]
    data = read_json(file_path)
    with open(file_path + ".clean", "w", encoding="utf-8") as f:
        f.write(json.dumps(data, indent=2))
